import { GoalCategory } from '@/app/actions/goals';

export interface GoalTemplate {
  id: string;
  category: GoalCategory;
  name: string;
  description: string;
  defaultTitle: string;
  defaultUnit?: string;
  defaultTarget?: number;
  goalType: 'numerical' | 'yesno';
  suggestedPeriod: 'monthly' | 'weekly';
  icon?: string;
}

export const GOAL_TEMPLATES: Record<GoalCategory, GoalTemplate[]> = {
  tasks: [
    {
      id: 'task-completion',
      category: 'tasks',
      name: 'Task Completion',
      description: 'Complete a specific number of tasks',
      defaultTitle: 'Complete {target} tasks',
      defaultUnit: 'tasks',
      defaultTarget: 20,
      goalType: 'numerical',
      suggestedPeriod: 'monthly',
    },
    {
      id: 'task-velocity',
      category: 'tasks',
      name: 'Task Velocity',
      description: 'Complete a percentage of high-priority tasks',
      defaultTitle: 'Complete {target}% of high-priority tasks',
      defaultUnit: '%',
      defaultTarget: 50,
      goalType: 'numerical',
      suggestedPeriod: 'weekly',
    },
    {
      id: 'task-status',
      category: 'tasks',
      name: 'Task Status Progress',
      description: 'Move tasks through status stages',
      defaultTitle: 'Move {target} tasks to completed',
      defaultUnit: 'tasks',
      defaultTarget: 10,
      goalType: 'numerical',
      suggestedPeriod: 'weekly',
    },
  ],
  features: [
    {
      id: 'feature-releases',
      category: 'features',
      name: 'Feature Releases',
      description: 'Release a number of features',
      defaultTitle: 'Release {target} features',
      defaultUnit: 'features',
      defaultTarget: 3,
      goalType: 'numerical',
      suggestedPeriod: 'monthly',
    },
    {
      id: 'feature-area',
      category: 'features',
      name: 'Feature by Area',
      description: 'Complete features in a specific area',
      defaultTitle: 'Complete {target} features in {area}',
      defaultUnit: 'features',
      defaultTarget: 5,
      goalType: 'numerical',
      suggestedPeriod: 'monthly',
    },
    {
      id: 'feature-status',
      category: 'features',
      name: 'Feature Status Progress',
      description: 'Move features through development stages',
      defaultTitle: 'Move {target} features to released',
      defaultUnit: 'features',
      defaultTarget: 2,
      goalType: 'numerical',
      suggestedPeriod: 'monthly',
    },
  ],
  bugs: [
    {
      id: 'bug-fixes',
      category: 'bugs',
      name: 'Bug Fixes',
      description: 'Resolve a number of bugs',
      defaultTitle: 'Resolve {target} bugs',
      defaultUnit: 'bugs',
      defaultTarget: 10,
      goalType: 'numerical',
      suggestedPeriod: 'weekly',
    },
    {
      id: 'critical-bugs',
      category: 'bugs',
      name: 'Critical Bug Resolution',
      description: 'Fix all critical bugs within timeframe',
      defaultTitle: 'Fix all critical bugs',
      defaultUnit: 'bugs',
      defaultTarget: 1,
      goalType: 'yesno',
      suggestedPeriod: 'weekly',
    },
    {
      id: 'bug-reduction',
      category: 'bugs',
      name: 'Bug Reduction',
      description: 'Reduce open bugs by percentage',
      defaultTitle: 'Reduce open bugs by {target}%',
      defaultUnit: '%',
      defaultTarget: 20,
      goalType: 'numerical',
      suggestedPeriod: 'monthly',
    },
  ],
  content: [
    {
      id: 'content-creation',
      category: 'content',
      name: 'Content Creation',
      description: 'Create a number of content pieces',
      defaultTitle: 'Create {target} articles',
      defaultUnit: 'articles',
      defaultTarget: 20,
      goalType: 'numerical',
      suggestedPeriod: 'monthly',
    },
    {
      id: 'content-requirements',
      category: 'content',
      name: 'Content Requirements',
      description: 'Complete content requirements',
      defaultTitle: 'Complete {target} content requirements',
      defaultUnit: 'requirements',
      defaultTarget: 5,
      goalType: 'numerical',
      suggestedPeriod: 'weekly',
    },
    {
      id: 'content-scheduling',
      category: 'content',
      name: 'Content Scheduling',
      description: 'Schedule content for upcoming period',
      defaultTitle: 'Schedule content for next {target} weeks',
      defaultUnit: 'weeks',
      defaultTarget: 4,
      goalType: 'numerical',
      suggestedPeriod: 'monthly',
    },
  ],
  meetings: [
    {
      id: 'meeting-attendance',
      category: 'meetings',
      name: 'Meeting Attendance',
      description: 'Attend all meetings of a specific type',
      defaultTitle: 'Attend all {type} meetings',
      defaultUnit: 'meetings',
      defaultTarget: 1,
      goalType: 'yesno',
      suggestedPeriod: 'monthly',
    },
    {
      id: 'action-items',
      category: 'meetings',
      name: 'Action Items Completion',
      description: 'Complete a percentage of meeting action items',
      defaultTitle: 'Complete {target}% of action items',
      defaultUnit: '%',
      defaultTarget: 80,
      goalType: 'numerical',
      suggestedPeriod: 'weekly',
    },
    {
      id: 'meeting-types',
      category: 'meetings',
      name: 'Meeting Types',
      description: 'Attend meetings of different types',
      defaultTitle: 'Attend {target} {type} meetings',
      defaultUnit: 'meetings',
      defaultTarget: 5,
      goalType: 'numerical',
      suggestedPeriod: 'monthly',
    },
  ],
  operations: [
    {
      id: 'order-processing',
      category: 'operations',
      name: 'Order Processing',
      description: 'Process a number of orders',
      defaultTitle: 'Process {target} orders',
      defaultUnit: 'orders',
      defaultTarget: 500,
      goalType: 'numerical',
      suggestedPeriod: 'monthly',
    },
    {
      id: 'quality-metrics',
      category: 'operations',
      name: 'Quality Metrics',
      description: 'Maintain quality accuracy rate',
      defaultTitle: 'Maintain {target}% accuracy rate',
      defaultUnit: '%',
      defaultTarget: 99,
      goalType: 'numerical',
      suggestedPeriod: 'monthly',
    },
    {
      id: 'turnaround-time',
      category: 'operations',
      name: 'Turnaround Time',
      description: 'Maintain average processing time',
      defaultTitle: 'Average processing time under {target} hours',
      defaultUnit: 'hours',
      defaultTarget: 2,
      goalType: 'numerical',
      suggestedPeriod: 'weekly',
    },
  ],
  team: [
    {
      id: 'team-engagement',
      category: 'team',
      name: 'Team Member Engagement',
      description: 'Assign tasks to all team members',
      defaultTitle: 'Assign tasks to all team members',
      defaultUnit: 'members',
      defaultTarget: 1,
      goalType: 'yesno',
      suggestedPeriod: 'monthly',
    },
    {
      id: 'cross-functional',
      category: 'team',
      name: 'Cross-functional Collaboration',
      description: 'Participate in cross-team meetings',
      defaultTitle: 'Participate in {target} cross-team meetings',
      defaultUnit: 'meetings',
      defaultTarget: 5,
      goalType: 'numerical',
      suggestedPeriod: 'monthly',
    },
  ],
  'time-based': [
    {
      id: 'daily-goals',
      category: 'time-based',
      name: 'Daily Goals',
      description: 'Complete tasks daily',
      defaultTitle: 'Complete {target} tasks daily',
      defaultUnit: 'tasks',
      defaultTarget: 3,
      goalType: 'numerical',
      suggestedPeriod: 'weekly',
    },
    {
      id: 'quarterly-goals',
      category: 'time-based',
      name: 'Quarterly Objectives',
      description: 'Achieve quarterly objectives',
      defaultTitle: 'Achieve Q{quarter} objectives',
      defaultUnit: 'objectives',
      defaultTarget: 1,
      goalType: 'yesno',
      suggestedPeriod: 'monthly',
    },
    {
      id: 'yearly-goals',
      category: 'time-based',
      name: 'Annual Goals',
      description: 'Annual revenue or performance target',
      defaultTitle: 'Annual revenue target',
      defaultUnit: 'revenue',
      defaultTarget: 1000000,
      goalType: 'numerical',
      suggestedPeriod: 'monthly',
    },
  ],
  percentage: [
    {
      id: 'completion-rate',
      category: 'percentage',
      name: 'Completion Rate',
      description: 'Achieve a completion rate percentage',
      defaultTitle: 'Achieve {target}% completion rate',
      defaultUnit: '%',
      defaultTarget: 90,
      goalType: 'numerical',
      suggestedPeriod: 'monthly',
    },
    {
      id: 'progress-milestone',
      category: 'percentage',
      name: 'Progress Milestone',
      description: 'Reach a progress milestone',
      defaultTitle: 'Reach {target}% milestone',
      defaultUnit: '%',
      defaultTarget: 50,
      goalType: 'numerical',
      suggestedPeriod: 'monthly',
    },
  ],
  'multi-metric': [
    {
      id: 'combined-kpis',
      category: 'multi-metric',
      name: 'Combined KPIs',
      description: 'Track multiple metrics together',
      defaultTitle: 'Achieve combined KPI targets',
      defaultUnit: 'points',
      defaultTarget: 100,
      goalType: 'numerical',
      suggestedPeriod: 'monthly',
    },
    {
      id: 'weighted-goals',
      category: 'multi-metric',
      name: 'Weighted Goals',
      description: 'Track goals with different weights',
      defaultTitle: 'Achieve weighted goal targets',
      defaultUnit: 'points',
      defaultTarget: 80,
      goalType: 'numerical',
      suggestedPeriod: 'monthly',
    },
  ],
  general: [
    {
      id: 'custom-numerical',
      category: 'general',
      name: 'Custom Numerical Goal',
      description: 'Create a custom numerical goal',
      defaultTitle: 'New Goal',
      defaultUnit: '',
      defaultTarget: 100,
      goalType: 'numerical',
      suggestedPeriod: 'monthly',
    },
    {
      id: 'custom-yesno',
      category: 'general',
      name: 'Custom Yes/No Goal',
      description: 'Create a custom yes/no goal',
      defaultTitle: 'New Goal',
      defaultUnit: '',
      defaultTarget: 1,
      goalType: 'yesno',
      suggestedPeriod: 'weekly',
    },
  ],
};

export const CATEGORY_LABELS: Record<GoalCategory, string> = {
  tasks: 'Tasks',
  features: 'Features',
  bugs: 'Bugs',
  content: 'Content',
  meetings: 'Meetings',
  operations: 'Operations',
  team: 'Team Collaboration',
  'time-based': 'Time-Based',
  percentage: 'Percentage',
  'multi-metric': 'Multi-Metric',
  general: 'General',
};

export const CATEGORY_DESCRIPTIONS: Record<GoalCategory, string> = {
  tasks: 'Track task completion and velocity',
  features: 'Monitor feature delivery and releases',
  bugs: 'Track bug resolution and reduction',
  content: 'Manage content creation and scheduling',
  meetings: 'Track meeting attendance and action items',
  operations: 'Monitor operational metrics (PrepCenter)',
  team: 'Team collaboration and engagement',
  'time-based': 'Daily, quarterly, and yearly goals',
  percentage: 'Percentage-based completion goals',
  'multi-metric': 'Combined and weighted metrics',
  general: 'Custom goals without specific category',
};

export function getTemplatesByCategory(category: GoalCategory): GoalTemplate[] {
  return GOAL_TEMPLATES[category] || [];
}

export function getAllTemplates(): GoalTemplate[] {
  return Object.values(GOAL_TEMPLATES).flat();
}

export function getTemplateById(id: string): GoalTemplate | undefined {
  return getAllTemplates().find(t => t.id === id);
}
